### ISSUE TITLE
ClassNotFoundException: org.apache.log4j.PropertyConfigurator [2.3.1]

### ISSUE THREAD

**Issue by Pyppe** [elastic/elasticsearch#17585]
**Elasticsearch version**: 2.3.1
**JVM version**: 1.8
**OS version**: Ubuntu 14.04
**Description of the problem including expected versus actual behavior**:
We have a custom build of elaticsearch with embedded plugins, which we build as a single JAR (using scala & sbt-assembly). Now, if we try to upgrade elasticsearch dependency from `2.2.0` to `2.3.1` we will get `java.lang.ClassNotFoundException: org.apache.log4j.PropertyConfigurator` on startup.
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/PropertyConfigurator
Likely root cause: java.lang.ClassNotFoundException: org.apache.log4j.PropertyConfigurator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:128)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:243)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

Everything works in `2.2.0` so I assume there is something fishy with the maven declarations?

**Comment by dadoonet** [comment]
I believe that you have to include it explicitly as it's marked as optional: https://github.com/elastic/elasticsearch/blob/2.x/core/pom.xml#L166-L175

**Comment by Pyppe** [comment]
Yeah, but why is it marked optional if you cannot to start the program without it?

**Comment by dadoonet** [comment]
Because you can provide another implementation if you wish.

**Comment by rmannibucau** [comment]
Hi got the same issue with 2.3.2,

https://github.com/elastic/elasticsearch/blob/2.x/core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java#L243 being called whatever config you do, https://github.com/elastic/elasticsearch/blob/2.x/core/src/main/java/org/elasticsearch/common/logging/log4j/LogConfigurator.java#L128 is triggered and load log4j so it is not optional so shouldn't be marked as such in the pom IMO.

Having a es.log flag == jul could allow to skip it and avoid this noclassdeffounderror.

**Comment by nik9000** [comment]
As of 2.3.something log4j isn't optional in the server. In the client it should be. The problem is that the client shares the same pom and jar as the server. Both of those things are known bad but not actively being worked on other than the initiative to provide a REST based java client.
