### ISSUE TITLE
BoundedBreakIteratorScanner throws IllegalStateException when used with SplittingBreakIterator

### ISSUE THREAD

**Issue by morning-color** [elastic/elasticsearch#143439]
### Elasticsearch Version

9.1.3 

### Java Version

JDK 25

### OS Version

Linux

### Problem Description

  `BoundedBreakIteratorScanner` throws `IllegalStateException: first() should not be called in this context` during the fetch/highlight phase when using `match_phrase_prefix` query with the default unified highlighter.

### Root Cause

`BoundedBreakIteratorScanner` is a custom `BreakIterator` subclass that intentionally does not implement the standard `BreakIterator` navigation methods (`first()`, `next()`, `last()`, `next(n)`, `previous()`), throwing `IllegalStateException` instead. It was designed to work only through the `preceding()`/`following()` call pattern.

However, Lucene's `UnifiedHighlighter` wraps user-provided `BreakIterator` instances with `SplittingBreakIterator` to handle multi-valued fields. `SplittingBreakIterator.following(offset)` calls `delegate.first()` when repositioning across segment boundaries, which triggers the exception.

This was previously masked by `CustomFieldHighlighter` which overrode `highlightOffsetsEnums()` with a copy of the old Lucene implementation (introduced in #51327 as a workaround for LUCENE-9093). After #96068 removed that workaround and delegated to `super.highlightOffsetsEnums()`, the issue resurfaced.

### Call Chain

```
FieldHighlighter.highlightOffsetsEnums()
  → SplittingBreakIterator.following(offset)
    → BoundedBreakIteratorScanner.first()
      → throws IllegalStateException
```

### Steps to Reproduce

```json
GET {index}/_search
{
  "query": {
    "match_phrase_prefix": {
      "{text_field}": {
        "query": "林林林林",
        "slop": 8
      }
    }
  },
  "highlight": {
    "fields": {
      "{text_field}": {}
    }
  }
}
```

The text field uses the default `unified` highlighter with `sentence` boundary scanner. The `match_phrase_prefix` query with CJK characters triggers prefix expansion that produces offset combinations hitting `SplittingBreakIterator`'s segment boundary repositioning logic, which calls `delegate.first()`.

Triggering conditions:
- `match_phrase_prefix` query + highlighting on the same field
- Default unified highlighter with sentence boundary scanner
- Multi-valued field (values joined with `\0` separator) or specific offset combinations from prefix expansion

### Stack Trace

```
java.lang.IllegalStateException: first() should not be called in this context
  at o.e.lucene.search.uhighlight.BoundedBreakIteratorScanner.first(BoundedBreakIteratorScanner.java:165)
  at o.a.lucene.search.uhighlight.SplittingBreakIterator.following(SplittingBreakIterator.java:183)
  at o.a.lucene.search.uhighlight.FieldHighlighter.highlightOffsetsEnums(FieldHighlighter.java:186)
  at o.e.lucene.search.uhighlight.CustomFieldHighlighter.highlightOffsetsEnums(CustomFieldHighlighter.java:118)
  at o.a.lucene.search.uhighlight.FieldHighlighter.highlightFieldForDoc(FieldHighlighter.java:86)
  at o.e.lucene.search.uhighlight.CustomFieldHighlighter.highlightFieldForDoc(CustomFieldHighlighter.java:75)
  at o.e.lucene.search.uhighlight.CustomUnifiedHighlighter.highlightField(CustomUnifiedHighlighter.java:152)
  at o.e.search.fetch.subphase.highlight.DefaultHighlighter.highlight(DefaultHighlighter.java:87)
```

### Expected Behavior

`BoundedBreakIteratorScanner` should fully implement the `BreakIterator` interface contract. When `first()` (or any other standard navigation method) is called, it should reset internal state and delegate to the underlying `mainBreak` iterator, rather than throwing an exception.

### Related

- #51327 — Original workaround in `CustomFieldHighlighter` for LUCENE-9093
- #96068 — Removed the workaround, re-exposing this issue
- [LUCENE-9093](https://issues.apache.org/jira/browse/LUCENE-9093) — Lucene change that originally triggered incompatibility

### Steps to Reproduce

1. Create an index with a text field using the default analyzer:

```json
PUT /test-index
{
  "mappings": {
    "properties": {
      "content": {
        "type": "text"
      }
    }
  }
}
```

2. Index a document with a multi-valued text field containing CJK characters:

```json
POST /test-index/_doc/1
{
  "content": ["林林林林总总的信息在这里", "另一个包含林林的文本段落"]
}
```

3. Execute a `match_phrase_prefix` query with highlighting on the same field:

```json
GET /test-index/_search
{
  "query": {
    "match_phrase_prefix": {
      "content": {
        "query": "林林林林",
        "slop": 8
      }
    }
  },
  "highlight": {
    "fields": {
      "content": {}
    }
  }
}
```

4. The search request returns a shard failure with `IllegalStateException`:

```
java.lang.IllegalStateException: first() should not be called in this context
  at o.e.lucene.search.uhighlight.BoundedBreakIteratorScanner.first(BoundedBreakIteratorScanner.java:165)
  at o.a.lucene.search.uhighlight.SplittingBreakIterator.following(SplittingBreakIterator.java:183)
  ...
```
