### ISSUE TITLE
ESQL: Fix mismatched error message on yaml test

### ISSUE THREAD

**Issue by GalLalouche** [elastic/elasticsearch#145102]
```
Expected: a string containing "line 1:56: Cannot use field [foo.bar] due to ambiguities being mapped as [2] incompatible types: [keyword] enforced by INSIST command, [unsupported] in [index4]"
     but: was "Found 1 problem
line 1:56: Cannot use field [foo.bar] due to ambiguities being mapped as [2] incompatible types: [keyword] enforced by INSIST command, and [unsupported] in index mappings"
> java.lang.AssertionError: 
  Expected: a string containing "line 1:56: Cannot use field [foo.bar] due to ambiguities being mapped as [2] incompatible types: [keyword] enforced by INSIST command, [unsupported] in [index4]"
       but: was "Found 1 problem
  line 1:56: Cannot use field [foo.bar] due to ambiguities being mapped as [2] incompatible types: [keyword] enforced by INSIST command, and [unsupported] in index mappings"
```
Caused by #143693.
