### PR TITLE
Upgrade OpenSAML to 5.2.3

### PR DESCRIPTION
**Pull request by slobodanadamovic**
Upgrades OpenSAML 4.x -> 5.2.3. OpenSAML 4.x reached end of life on 2024-09-01 and no longer receives security patches.

## Shadow library

The `es-opensaml-security-api` shadow jar predates this change (introduced in #98199 to prevent non-FIPS BouncyCastle from loading on FIPS JVMs via the `NamedCurve` SPI). OpenSAML 5 still ships the same SPI file and the same hard dependency on non-FIPS BC, so the workaround is kept as-is.

Additionally, `cryptacular 1.3.0` (pulled in by OpenSAML 5) instantiates `BouncyCastleProvider` in a constant-pool reference that the Java classloader resolves eagerly, causing `NoClassDefFoundError` in FIPS mode even on code paths that never call the offending method. The shadow jar embeds a patched `CertUtil` that removes the reference.

## Artifact changes

- `opensaml-core` splits into `opensaml-core-api` + `opensaml-core-impl`
- `net.shibboleth.utilities:java-support` becomes `net.shibboleth:shib-support` plus three new sibling modules (`shib-security`, `shib-networking`, `shib-velocity`)
- `xmlsec` bumps to 3.0.6 (required by OpenSAML 5)
- `cryptacular` bumps to 1.3.0, `metrics-core` to 4.2.39

## Apache HttpClient  5

OpenSAML 5 dropped all `org.apache.http` references and requires `httpclient5`. 
The `SamlMetadataResolver` is updated to use an `httpclient5` client.

### CODE REVIEW

**Review by n1v0lg — APPROVED** [review]
LGTM -- if CI is happy I am happy
