### ISSUE TITLE
Elasticsearch 2.4.4 - compilation failure with groovy dynamic scripting which works fine in 2.1.1

### ISSUE THREAD

**Issue by parvathy-u** [elastic/elasticsearch#25569]
Hi,
I am using dynamic scripting with groovy in Elasticsearch 2.4.4. The script gives a compilation error, whereas the same script was working fine in Elasticsearch 2.1.1. I have verified the script complies fine in a groovy console.

_Error: 
caused_by":{"type":"script_exception","reason":"Error compiling script b065d53a6f4fa2969360ce7776fc0abfa1cd1f21","caused_by":{"type":"multiple_compilation_errors_exception","reason":"startup failed:\nb065d53a6f4fa2969360ce7776fc0abfa1cd1f21: 28: unable to resolve class LinkedHashMap_ 

_Code Snippet:

if (!found) {
  target.paths.add((LinkedHashMap)source);
}_

Any help in this regard is greatly appreciated. 
Thanks!
Parvathy.

**Comment by rjernst** [comment]
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.

Security manager limitations were added in 2.2. See the [scripting docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-scripting-security.html) for customizing the whitelisted classes.
