### ISSUE TITLE
Groovy script in aggregation not working in 2.0

### ISSUE THREAD

**Issue by reflection** [elastic/elasticsearch#14273]
Here's the aggregation expressed in elasticsearch-dsl-py (which works fine in 1.x):
```
s.aggs \
  .bucket('hour', 'terms', script= \
          'use(groovy.time.TimeCategory) { \
            new Date(doc["timestamp"].value).format("HH") \
          }', size=0, order={'_term': 'asc'}) \
  .metric('bandwidth', 'sum', field='size') \
    .bucket('action', 'terms', field='action', size=0) \
    .metric('bandwidth', 'sum', field='size')
```
In 2.0 we get this error:
```
RemoteTransportException[[Longshot][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: 
QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: 
GroovyScriptExecutionException[failed to run inline script 
[use(groovy.time.TimeCategory) {                 new Date(doc["timestamp"].value).format("HH")               }] using lang [groovy]]; nested: 
NoClassDefFoundError[Could not initialize class org.codehaus.groovy.vmplugin.v7.IndyInterface];
```
If we can no longer use groovy.time.TimeCategory, is there an alternative way to get hour buckets coalesced across multiple days from timestamps?  Thanks in advance!

**Comment by pickypg** [comment]
Can you check the log of the node for the cause of the `Could not initialize class org.codehaus.groovy.vmplugin.v7.IndyInterface` error? That's not the root error, rather something else failed to let that happen.

**Comment by reflection** [comment]
This is the full error from a recent run: https://gist.github.com/reflection/a62d981f9f1e499e7c8e

**Comment by pickypg** [comment]
Hi @reflection, can you try to find the original run of the script? Once that kind of error happens, it repeats? _If_ you can restart the node, then run it to find the first occurrence (if it's difficult without restarting), then that would be good.

**Comment by rmuir** [comment]
I think its a legit bug: see http://www.groovy-lang.org/indy.html

Even though we have not enabled indy (https://github.com/elastic/elasticsearch/pull/8201), we ship an indy jar in 2.0, hence it still will be used for core groovy classes. 

To fix this for 2.0, we'd need to either backport that change completely, or at least backport policy file changes from that PR. And of course a test that is like @reflection script that uses one of these classes so we know its working.

**Comment by clintongormley** [comment]
Would a workaround be to delete the indy jar for now?

**Comment by rmuir** [comment]
no clue. first things first, we need a failing unit test.

**Comment by rmuir** [comment]
i also don't think we should encourage users to manually mess with jars like that. we should just fix the bug....

**Comment by pickypg** [comment]
Yeah, that's why I was trying to find the core error. Curious if it's a security manager error that trips up the `IndyInterface` (as we found with #8201) or if it's something else.

**Comment by rmuir** [comment]
I'm sure its probably that. You probably get NoClassDefFound because there was an earlier security exception before when trying to do the static init, as the indy stuff will not work.

So I think we just need to have a test that uses standard groovy function to ensure invokeDynamic is working.

**Comment by pickypg** [comment]
I just tried this in a script field in 2.0 RC1 and it did not fail:

```http
PUT /test/type/1
{
  "message" : "this is text",
  "timestamp" : "2015-10-24T17:12:00.000Z"
}

GET /test/_search
{
  "script_fields": {
    "hours": {
      "script": "use(groovy.time.TimeCategory) { new Date(doc['timestamp'].value).format('HH') }"
    }
  }
}
```

This generated the `ExceptionInInitializerError`:

```
Caused by: java.lang.ExceptionInInitializerError
        at org.codehaus.groovy.vmplugin.v7.Java7.invalidateCallSites(Java7.java:66)
        at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.newScope(GroovyCategorySupport.java:78)
        at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:109)
        at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.access$400(GroovyCategorySupport.java:68)
        at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:252)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.use(DefaultGroovyMethods.java:406)
        at org.codehaus.groovy.runtime.dgm$755.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:251)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
        at 6500c935a9b77886d78797d577be9c2be71f03d0.run(6500c935a9b77886d78797d577be9c2be71f03d0:1)
        at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:248)
        ... 10 more
Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "groovy.indy.logging" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1294)
        at java.lang.System.getProperty(System.java:717)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.<clinit>(IndyInterface.java:76)
        ... 24 more
```

Core caused by:

```
 java.security.AccessControlException: access denied ("java.util.PropertyPermission" "groovy.indy.logging" "read")
```

**Comment by pickypg** [comment]
Related to https://github.com/apache/incubator-groovy/pull/119

**Comment by rmuir** [comment]
To me the safest option for a 2.0.x fix would be:
* add test to GroovySecurityIT
* backport https://github.com/elastic/elasticsearch/pull/8201 in its entirety but just change default to false. it can be enabled in 2.1

**Comment by s1monw** [comment]
@reflection can you tell me what what JVM you are using?

**Comment by s1monw** [comment]
this is fixed by #14283 for `2.0.1` the first time the class is accessed we get a security excepiton and all subsequent tries get a shadowing `NoClassDefFoundError`.
