### ISSUE TITLE
ESQL: unexpected verification_exception for same field name in two indices (union types)

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#111452]
### Description

test1 index

```
{
    "mappings": {
        "properties": {
            "x": {
                "type": "keyword"
            }
        }
    }
}
```

test2 index

```
{
    "mappings": {
        "properties": {
            "x": {
                "type": "long"
            },
            "whatever": {
                "type": "text"
            }
        }
    }
}
```

`from test* | rename whatever as foo` results in 

```
     "type": "verification_exception",
        "reason": "Found 1 problem\nline 1:1: Cannot use field [x] due to ambiguities being mapped as [2] incompatible types: [keyword] in [test1], [long] in [test2]",
        "stack_trace": "org.elasticsearch.xpack.esql.VerificationException: Found 1 problem\nline 1:1: Cannot use field [x] due to ambiguities being mapped as [2] incompatible types: [keyword] in [test1], [long] in [test2]
```

**Comment by alex-spies** [comment]
I can confirm that the given query used to work on 8.14, but breaks on current main and on 8.15.

**Comment by alex-spies** [comment]
There's a workaround: you can just `DROP` the offending field before the `RENAME`.

```
from test* | drop x | rename whatever as foo
```
