### PR TITLE
Fix main compilation errors

### PR DESCRIPTION
**Pull request by joshua-adams-1**
I merged #145803 but it conflicted with #145488 merged yesterday

### CODE REVIEW

**Review by PeteGillinElastic — APPROVED** [review]

**Review by samxbr — APPROVED** [review]

**Comment by joshua-adams-1** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/pull/146014
