### ISSUE TITLE
Regression: Zendesk connector (maybe generic)

### ISSUE THREAD

**Issue by Zetanova** [elastic/elasticsearch#113361]
### Elasticsearch Version

8.15.1

### Java Version

_bundled_

### OS Version

docker

### Problem Description

After update from 8.11.3 to 8.15.1 the zendesk connector errors with `org.bouncycastle.asn1.DERIA5String org.bouncycastle.asn1.DERIA5String.getInstance(java.lang.Object)`  [releated issue](https://github.com/bcgit/bc-java/issues/1614)

### Steps to Reproduce

After update from 8.11.3 to 8.15.1 a zendesk connectors and most likely others will produce this error

### Logs (if relevant)

Unknown problem occurred when syncing.

org.bouncycastle.asn1.DERIA5String org.bouncycastle.asn1.DERIA5String.getInstance(java.lang.Object)

Unknown problem occurred when syncing.
/usr/share/enterprise-search/lib/war/gems/gems/activesupport-6.1.7.4/lib/active_support/tagged_logging.rb:99:in `tagged\u0027: undefined method `tagged\u0027 for #\u003cProc:0x18ab23a5\u003e (NoMethodError)\n\tfrom /usr/share/enterprise-search/lib/war/connectors/lib/connectors/work/job_tagged_logger.class:13:in `block in JobTaggedLogger\u0027\n\tfrom /usr/share/enterprise-search/lib/war/connectors/lib/connectors/work/index.class:9:in `run\u0027\n\tfrom /usr/share/enterprise-search/lib/war/connectors/lib/connectors/work/abstract_extractor_work.class:138:in `execute\u0027\n\tfrom /usr/share/enterprise-search/lib/war/connectors/lib/connectors/workers/extract_worker.class:7:in `block in run\u0027\n\tfrom /usr/share/enterprise-search/lib/war/gems/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute\u0027\n\tfrom /usr/share/enterprise-search/lib/war/gems/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute\u0027\n\tfrom /usr/share/enterprise-search/lib/war/connectors/config/initializers/concurrent.class:18:in `block in realize\u0027\n\tfrom /usr/share/enterprise-search/lib/war/gems/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/java_executor_service.rb:79:in `run
