### ISSUE TITLE
Exception in Logstash 1.5.0

### ISSUE THREAD

**Issue by aimdev** [elastic/elasticsearch#11217]
While reloading data (which worked ok on 1.4.2), this occured
Exception in filterworker {"exception"=>#<NoMethodError: undefined method `to_hash' for "*AS18144 Energia Communications,Inc.":String>, "backtrace"=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-0.1.9/lib/logstash/filters/geoip.rb:119:in `filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/filters/base.rb:162:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/filters/base.rb:159:in `multi_filter'", "(eval):569:in `cond_func_7'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):561:in `cond_func_7'", "(eval):412:in `filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:219:in `filterworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:156:in `start_filters'"], :level=>:error}

**Comment by clintongormley** [comment]
Hi @aimdev 

Please open this issue on the https://github.com/logstash-plugins/logstash-filter-geoip issues list instead
