### ISSUE TITLE
Build on Windows 2012 fails with compilation failure from assigning to final variables

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#16097]
Compile issue that seems only to happen on Windows jdk as seen here:

http://build-us-00.elastic.co/job/es_core_master_window-2012/2315/

```
Compiling with Java command line compiler 'y:\jdk8\8u11\bin\javac'.
Starting process 'command 'y:\jdk8\8u11\bin\javac''. Working directory: Y:\jenkins\workspace\es_core_master_window-2012\core Command: y:\jdk8\8u11\bin\javac -J-Xmx1g @Y:\jenkins\workspace\es_core_master_window-2012\core\build\tmp\compileJava\java-compiler-args.txt
Successfully started process 'command 'y:\jdk8\8u11\bin\javac''
Y:\jenkins\workspace\es_core_master_window-2012\core\src\main\java\org\elasticsearch\cluster\metadata\AutoExpandReplicas.java:44: error: cannot assign a value to final variable min
            min = Integer.parseInt(sMin);
            ^
Y:\jenkins\workspace\es_core_master_window-2012\core\src\main\java\org\elasticsearch\cluster\metadata\AutoExpandReplicas.java:50: error: cannot assign a value to final variable max
            max = Integer.MAX_VALUE;
            ^
Y:\jenkins\workspace\es_core_master_window-2012\core\src\main\java\org\elasticsearch\cluster\metadata\AutoExpandReplicas.java:53: error: cannot assign a value to final variable max
                max = Integer.parseInt(sMax);
                ^
```

The same code compiles fine on other systems. I'll go ahead and remove the offending `final` modifier for now, but leave a comment linking to this issue.

**Comment by javanna** [comment]
isn't it a jvm bug? shouldn't we upgrade to a more recent jdk instead of changing the code? I wonder if  the fact that it's a windows machine matters.

**Comment by ywelsch** [comment]
JDK Version identifies as `Oracle Corporation 1.8.0_11 [Java HotSpot(TM) 64-Bit Server VM 25.11-b03]`. Can we update this to a more recent version @drewr ?

**Comment by cbuescher** [comment]
Could be related to http://bugs.java.com/view_bug.do?bug_id=8051958, since it's code inside a lambda.
Pushing the fix wasn't meant as a permanent solution, @s1monw suggested to do it to get the windows build working again, following up on it with this issue, but I'm also happy to wait with it to see if updating the jdk helps.

**Comment by cbuescher** [comment]
Master also doesn't compile on my machine (Mac OS) with jdk 1.8.0_25 and 1.8.0_31. More resent version (I tried u60 and u66) work.

**Comment by cbuescher** [comment]
Same here, that machine probably also needs a fresher jdk version:

http://build-us-00.elastic.co/job/es_core_master_window-2008/

**Comment by jasontedor** [comment]
> Master also doesn't compile on my machine (Mac OS) with jdk 1.8.0_25 and 1.8.0_31. More recent version (I tried u60 and u66) work.

@cbuescher The same compiler bug, or are you seeing type inference errors?

**Comment by cbuescher** [comment]
@jasontedor Looks the same to me. I'd say I push the fix to remove the `final` modifier for now, can be re-added once those jdks have been updated, wdyt?

**Comment by jasontedor** [comment]
@cbuescher Okay, I think that it is fixed in 8u40 by a backport of the bug you linked to in [JDK-8052388](http://bugs.java.com/view_bug.do?bug_id=8052388), and I confirmed that it fails on 8u31 on my machine too, but succeeds on 8u40.

**Comment by cbuescher** [comment]
Pushed temporary fix with df5f1b1. We can revert this once infra has upgraded those servers.

**Comment by cbuescher** [comment]
@jasontedor thanks for taking care of this, while http://build-us-00.elastic.co/job/es_core_master_window-2008/ looks good now, last build on http://build-us-00.elastic.co/job/es_core_master_window-2012/ still seems to hang. Will ping infra in above ticket, maybe they can abort the hanging build
